syntax = "proto3";
package fixbug;

// 定义下面得选项，默认生成service服务
option cc_generic_services = true;

message ResultCode
{
    int32 errcode = 1;
    bytes errmsg = 2;
}

enum Sex
{
    MAN = 0;
    WOMAN = 1;
}

message GetFriendListsRequest
{
    uint32 userid = 1;
}

message User
{
    bytes name = 1;
    uint32 age = 2;
    Sex sex = 3;
}

message GetFriendListsResponse
{
    ResultCode result = 1;
    repeated bytes friends = 2;
}

service FriendServiceRpc
{
    rpc GetFriendsList(GetFriendListsRequest) returns(GetFriendListsResponse);
}